### ISSUE TITLE
Exception from HRESULT: 0x87B20C05

### ISSUE THREAD

**Issue by welikoiwanenko** [welikoiwanenko/Pikabu#17]
``` bash
at Microsoft.Phone.TaskModel.Interop.TaskNativeMethods.GetCurrentOrientation(UInt32 taskId, Orientations& currentOrientation)
   at Microsoft.Phone.TaskModel.Interop.Task.GetCurrentOrientation()
   at Microsoft.Phone.Controls.PhoneApplicationPage.UpdatePageOrientation()
   at Microsoft.Phone.Controls.PhoneApplicationPage.UpdateCurrentVisualState()
   at Microsoft.Phone.Controls.PhoneApplicationPage.HandleVisibleRegionChange()
   at Microsoft.Phone.Controls.PhoneApplicationPage.OnVisibleRegionChange()
   at Microsoft.Phone.TaskModel.Interop.Task.FireOnVisibleRegionChange()
```

**Comment by umausp** [comment]
i also get same exception frequently any idea solution ?
